function dS = MSDdyn3D(in1)
%MSDdyn3D
%    dS = MSDdyn3D(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    16-Apr-2025 15:59:25

alpha_n = in1(:,1);
g = in1(:,2);
k_n = in1(:,3);
m_n = in1(:,4);
omega_n = in1(:,5);
w = in1(:,6);
x_ddot = in1(:,7);
x_dot_n = in1(:,8);
x_n = in1(:,9);
y_ddot = in1(:,10);
y_dot_n = in1(:,11);
y_n = in1(:,12);
z_ddot = in1(:,13);
zeta_n = in1(:,14);
t2 = g.^2;
t3 = omega_n.^2;
t5 = omega_n.^5;
t6 = x_dot_n.^2;
t7 = x_n.^2;
t8 = y_dot_n.^2;
t9 = y_n.^2;
t10 = 1.0./m_n;
t11 = w-1.0;
t4 = t3.^2;
t14 = t7+t9;
t12 = t4.*t7;
t13 = t4.*t9;
t15 = t14.^t11;
t16 = t2+t12+t13;
t17 = 1.0./t16;
dS = [x_dot_n;y_dot_n;-t10.*t17.*(m_n.*t2.*x_ddot+m_n.*t13.*x_ddot+m_n.*t2.*t3.*x_n+m_n.*t4.*t6.*x_n+m_n.*t4.*t8.*x_n+alpha_n.*k_n.*t2.*t15.*x_n+g.*m_n.*t3.*x_n.*z_ddot+m_n.*omega_n.*t2.*x_dot_n.*zeta_n.*2.0+m_n.*t5.*t7.*x_dot_n.*zeta_n.*2.0+m_n.*t5.*t9.*x_dot_n.*zeta_n.*2.0-m_n.*t4.*x_n.*y_ddot.*y_n);-t10.*t17.*(m_n.*t2.*y_ddot+m_n.*t12.*y_ddot+m_n.*t2.*t3.*y_n+m_n.*t4.*t6.*y_n+m_n.*t4.*t8.*y_n+alpha_n.*k_n.*t2.*t15.*y_n+g.*m_n.*t3.*y_n.*z_ddot+m_n.*omega_n.*t2.*y_dot_n.*zeta_n.*2.0+m_n.*t5.*t7.*y_dot_n.*zeta_n.*2.0+m_n.*t5.*t9.*y_dot_n.*zeta_n.*2.0-m_n.*t4.*x_ddot.*x_n.*y_n)];
end
