function Sd =odeP_4D_roty(t,S,time,d_n,g,l_n,m_n,omega_n,psi,psi_dot,psi_ddot,x_ddot,y_ddot,z_ddot,zeta_n)

%--------------------------------------------------------------------------
% ODE of P 4DOF Model
%    Auto-generated by MATLAB Symbolic Toolbox
%--------------------------------------------------------------------------

Sd = zeros(4,1);

phi_y = S(1);
phi_x = S(2);
phi_dot_y = S(3);
phi_dot_x = S(4);

if t >= 0 && t <= time(end)
   x_ddot  = spline(time,x_ddot,t);
   y_ddot  = spline(time,y_ddot,t);
   z_ddot  = spline(time,z_ddot,t);
   psi  = spline(time,psi,t);
   psi_dot  = spline(time,psi_dot,t);
   psi_ddot  = spline(time,psi_ddot,t);
else
   x_ddot  = 0;
   y_ddot  = 0;
   z_ddot  = 0;
   psi  = 0;
   psi_dot  = 0;
   psi_ddot  = 0;
end

% Equations of Motion
Sd = Pdyn4D_roty([d_n,g,l_n,m_n,omega_n,phi_dot_x,phi_dot_y,phi_x,phi_y,psi,psi_ddot,psi_dot,x_ddot,y_ddot,z_ddot,zeta_n]);