function Sd =odeP_4D_rotz(t,S,time,g,l_n,m_n,omega_n,theta_0,theta_dot_0,theta_ddot_0,x_ddot,y_ddot,z_ddot,zeta_n)

%--------------------------------------------------------------------------
% ODE of P 4DOF Model
%    Auto-generated by MATLAB Symbolic Toolbox
%--------------------------------------------------------------------------

Sd = zeros(4,1);

phi_y = S(1);
phi_x = S(2);
phi_dot_y = S(3);
phi_dot_x = S(4);

if t >= 0 && t <= time(end)
   x_ddot  = spline(time,x_ddot,t);
   y_ddot  = spline(time,y_ddot,t);
   z_ddot  = spline(time,z_ddot,t);
   theta_0  = spline(time,theta_0,t);
   theta_dot_0  = spline(time,theta_dot_0,t);
   theta_ddot_0  = spline(time,theta_ddot_0,t);
else
   x_ddot  = 0;
   y_ddot  = 0;
   z_ddot  = 0;
   theta_0  = 0;
   theta_dot_0  = 0;
   theta_ddot_0  = 0;
end

% Equations of Motion
Sd = Pdyn4D_rotz([g,l_n,m_n,omega_n,phi_dot_x,phi_dot_y,phi_x,phi_y,theta_0,theta_ddot_0,theta_dot_0,x_ddot,y_ddot,z_ddot,zeta_n]);