function dS = Pdyn4D_roty(in1)
%Pdyn4D_roty
%    dS = Pdyn4D_roty(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    07-Jul-2025 14:25:55

d_n = in1(:,1);
g = in1(:,2);
l_n = in1(:,3);
m_n = in1(:,4);
omega_n = in1(:,5);
phi_x = in1(:,8);
phi_y = in1(:,9);
phi_dot_x = in1(:,6);
phi_dot_y = in1(:,7);
psi = in1(:,10);
psi_dot = in1(:,12);
psi_ddot = in1(:,11);
x_ddot = in1(:,13);
y_ddot = in1(:,14);
z_ddot = in1(:,15);
zeta_n = in1(:,16);
t2 = cos(phi_x);
t3 = cos(phi_y);
t4 = cos(psi);
t5 = sin(phi_x);
t6 = sin(phi_y);
t7 = sin(psi);
t8 = phi_y+psi;
t9 = phi_x.*2.0;
t10 = psi_dot.^2;
t13 = 1.0./l_n;
t15 = 1.0./m_n;
t11 = sin(t9);
t12 = sin(t8);
t14 = t13.^2;
t16 = 1.0./t2;
t17 = l_n.*m_n.*t3.*t4.*t5;
t18 = l_n.*m_n.*t5.*t6.*t7;
t19 = -t18;
t20 = t17+t19;
dS = [phi_dot_y;phi_dot_x;-g.*t12.*t13.*t16+phi_dot_x.*psi_dot.*t5.*t16.*2.0-t12.*t13.*t16.*z_ddot+t13.*t16.*x_ddot.*cos(t8)+phi_dot_y.*t13.*t15.*t16.*(l_n.*m_n.*phi_dot_x.*t5.*2.0-l_n.*m_n.*omega_n.*t2.*zeta_n.*2.0)+d_n.*t6.*t10.*t13.*t16+psi_ddot.*t13.*t15.*t16.*(d_n.*m_n.*t3-l_n.*m_n.*t2);phi_dot_y.^2.*t11.*(-1.0./2.0)-phi_dot_y.*psi_dot.*t11-omega_n.*phi_dot_x.*zeta_n.*2.0-t2.*t13.*y_ddot-g.*t14.*t15.*t20-t14.*t15.*t20.*z_ddot-t14.*t15.*x_ddot.*(l_n.*m_n.*t3.*t5.*t7+l_n.*m_n.*t4.*t5.*t6)-t10.*t14.*t15.*((m_n.*t11)./(t14.*2.0)-d_n.*l_n.*m_n.*t3.*t5)-d_n.*psi_ddot.*t5.*t6.*t13];
end
