function Sd =odeMSD_4D_roty(t,S,time,h,h_n,l_n,omega_n,psi,psi_dot,psi_ddot,x_ddot,y_ddot,z_ddot,zeta_n)

%--------------------------------------------------------------------------
% ODE of MSD 4DOF Model
%    Auto-generated by MATLAB Symbolic Toolbox
%--------------------------------------------------------------------------

Sd = zeros(4,1);

x_n = S(1);
y_n = S(2);
x_dot_n = S(3);
y_dot_n = S(4);

if t >= 0 && t <= time(end)
   x_ddot  = spline(time,x_ddot,t);
   y_ddot  = spline(time,y_ddot,t);
   z_ddot  = spline(time,z_ddot,t);
   psi  = spline(time,psi,t);
   psi_dot  = spline(time,psi_dot,t);
   psi_ddot  = spline(time,psi_ddot,t);
else
   x_ddot  = 0;
   y_ddot  = 0;
   z_ddot  = 0;
   psi  = 0;
   psi_dot  = 0;
   psi_ddot  = 0;
end

% Equations of Motion
Sd = MSDdyn4D_roty([h,h_n,l_n,omega_n,psi,psi_ddot,psi_dot,x_ddot,x_dot_n,x_n,y_ddot,y_dot_n,y_n,z_ddot,zeta_n]);