function Sd =odeMSD_3D(t,S,time,alpha_n,g,k_n,m_n,omega_n,w,x_ddot,y_ddot,z_ddot,zeta_n)

%--------------------------------------------------------------------------
% ODE of MSD 3DOF Model
%    Auto-generated by MATLAB Symbolic Toolbox
%--------------------------------------------------------------------------

Sd = zeros(4,1);

x_n = S(1);
y_n = S(2);
x_dot_n = S(3);
y_dot_n = S(4);

if t >= 0 && t <= time(end)
   x_ddot  = spline(time,x_ddot,t);
   y_ddot  = spline(time,y_ddot,t);
   z_ddot  = spline(time,z_ddot,t);
else
   x_ddot  = 0;
   y_ddot  = 0;
   z_ddot  = 0;
end

% Equations of Motion
Sd = MSDdyn3D([alpha_n,g,k_n,m_n,omega_n,w,x_ddot,x_dot_n,x_n,y_ddot,y_dot_n,y_n,z_ddot,zeta_n]);