function x = UR_FK(in1)
%UR_FK
%    X = UR_FK(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    16-Sep-2024 16:13:32

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q5);
t5 = cos(q6);
t6 = sin(q1);
t7 = sin(q5);
t8 = sin(q6);
t9 = q2+q3;
t10 = cos(t9);
t11 = q4+t9;
t13 = t2.*t7;
t15 = t6.*t7;
t16 = t3.*(1.7e+1./4.0e+1);
t12 = cos(t11);
t14 = sin(t11);
t20 = t10.*3.922e-1;
t17 = t2.*t4.*t12;
t18 = t4.*t6.*t12;
t23 = t16+t20;
t19 = -t18;
t21 = t15+t17;
t22 = t13+t19;
mt1 = [t5.*t21-t2.*t8.*t14,-t5.*t22-t6.*t8.*t14,t8.*t12+t4.*t5.*t14,0.0,-t8.*t21-t2.*t5.*t14,t8.*t22-t5.*t6.*t14,t5.*t12-t4.*t8.*t14,0.0,t4.*t6-t12.*t13,-t2.*t4-t12.*t15,-t7.*t14,0.0,t6.*1.333e-1+t4.*t6.*9.96e-2+t2.*t14.*9.97e-2-t2.*t23-t12.*t13.*9.96e-2,t2.*(-1.333e-1)-t2.*t4.*9.96e-2+t6.*t14.*9.97e-2-t12.*t15.*9.96e-2-t6.*t23];
mt2 = [t12.*(-9.97e-2)-sin(q2).*(1.7e+1./4.0e+1)-sin(t9).*3.922e-1-t7.*t14.*9.96e-2+1.3e+1./8.0e+1,1.0];
x = reshape([mt1,mt2],4,4);
end
