function dS = Pdyn4D_rotz(in1)
%Pdyn4D_rotz
%    dS = Pdyn4D_rotz(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Apr-2025 10:52:09

g = in1(:,1);
l_n = in1(:,2);
m_n = in1(:,3);
omega_n = in1(:,4);
phi_x = in1(:,7);
phi_y = in1(:,8);
phi_dot_x = in1(:,5);
phi_dot_y = in1(:,6);
theta_0 = in1(:,9);
theta_dot_0 = in1(:,11);
theta_ddot_0 = in1(:,10);
x_ddot = in1(:,12);
y_ddot = in1(:,13);
z_ddot = in1(:,14);
zeta_n = in1(:,15);
t2 = cos(phi_x);
t3 = cos(phi_y);
t4 = cos(theta_0);
t5 = sin(phi_x);
t6 = sin(phi_y);
t7 = sin(theta_0);
t8 = theta_dot_0.^2;
t9 = 1.0./l_n;
t11 = 1.0./m_n;
t10 = t9.^2;
t12 = 1.0./t2;
dS = [phi_dot_y;phi_dot_x;phi_dot_x.*t3.*theta_dot_0.*2.0+t3.*t6.*t8-g.*t6.*t9.*t12+t3.*t5.*t12.*theta_ddot_0-t6.*t9.*t12.*z_ddot+phi_dot_y.*t9.*t11.*t12.*(l_n.*m_n.*phi_dot_x.*t5.*2.0-l_n.*m_n.*omega_n.*t2.*zeta_n.*2.0)-t3.*t4.*t9.*t12.*x_ddot-t3.*t7.*t9.*t12.*y_ddot;-t6.*theta_ddot_0-(phi_dot_y.^2.*sin(phi_x.*2.0))./2.0-omega_n.*phi_dot_x.*zeta_n.*2.0-g.*t3.*t5.*t9-t3.*t5.*t9.*z_ddot-phi_dot_y.*t3.*1.0./t12.^2.*theta_dot_0.*2.0+t2.*t3.^2.*t5.*t8+t10.*t11.*x_ddot.*(l_n.*m_n.*t2.*t7+l_n.*m_n.*t4.*t5.*t6)-t10.*t11.*y_ddot.*(l_n.*m_n.*t2.*t4-l_n.*m_n.*t5.*t6.*t7)];
end
