function dS = MSDdyn4D_roty(in1)
%MSDdyn4D_roty
%    dS = MSDdyn4D_roty(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-Jul-2025 14:23:05

h = in1(:,1);
h_n = in1(:,2);
l_n = in1(:,3);
omega_n = in1(:,4);
psi = in1(:,5);
psi_dot = in1(:,7);
psi_ddot = in1(:,6);
x_ddot = in1(:,8);
x_dot_n = in1(:,9);
x_n = in1(:,10);
y_ddot = in1(:,11);
y_dot_n = in1(:,12);
y_n = in1(:,13);
z_ddot = in1(:,14);
zeta_n = in1(:,15);
t2 = cos(psi);
t3 = sin(psi);
t4 = l_n.^2;
t5 = l_n.^3;
t6 = omega_n.^2;
t7 = psi_dot.^2;
t8 = x_dot_n.^2;
t9 = x_n.^2;
t10 = x_n.^3;
t11 = y_dot_n.^2;
t12 = y_n.^2;
t13 = y_n.^3;
t14 = l_n.*t9;
t15 = l_n.*t12;
t16 = t5+t14+t15;
t17 = 1.0./t16;
mt1 = [x_dot_n;y_dot_n;t17.*(psi_ddot.*t12.^2-t3.*t4.^2.*t6.*2.0+h.*psi_ddot.*t5+h.*psi_ddot.*t15+h_n.*psi_ddot.*t5.*2.0+h_n.*psi_ddot.*t15.*2.0-l_n.*t7.*t10-psi_ddot.*t4.*t9+psi_ddot.*t4.*t12+psi_ddot.*t9.*t12+l_n.*t8.*x_n.*2.0+l_n.*t11.*x_n.*2.0+psi_dot.*t13.*y_dot_n.*4.0+t2.*t5.*x_ddot.*2.0+t2.*t15.*x_ddot.*2.0-t5.*t7.*x_n.*2.0-t7.*t15.*x_n.*3.0-t3.*t5.*z_ddot.*2.0-t3.*t15.*z_ddot.*2.0-h.*t4.*t7.*x_n-h_n.*t4.*t7.*x_n.*2.0-t3.*t4.*t6.*t12.*2.0+t2.*t5.*t6.*x_n.*2.0+psi_dot.*t12.*x_dot_n.*x_n.*4.0+omega_n.*t5.*x_dot_n.*zeta_n.*4.0+omega_n.*t14.*x_dot_n.*zeta_n.*4.0+omega_n.*t15.*x_dot_n.*zeta_n.*4.0+psi_dot.*t4.*y_dot_n.*y_n.*4.0-l_n.*x_n.*y_ddot.*y_n.*2.0+t3.*t4.*x_ddot.*x_n.*2.0+t2.*t4.*x_n.*z_ddot.*2.0).*(-1.0./2.0)];
mt2 = [t17.*(t5.*y_ddot.*2.0+t14.*y_ddot.*2.0-l_n.*t7.*t13+l_n.*t8.*y_n.*2.0+l_n.*t11.*y_n.*2.0-psi_ddot.*t13.*x_n-psi_ddot.*t10.*y_n+t7.*t14.*y_n-h.*t4.*t7.*y_n-h_n.*t4.*t7.*y_n.*2.0+t2.*t5.*t6.*y_n.*2.0-psi_dot.*t4.*x_dot_n.*y_n.*4.0-psi_dot.*t9.*x_dot_n.*y_n.*4.0-psi_dot.*t12.*x_n.*y_dot_n.*4.0-psi_ddot.*t4.*x_n.*y_n.*2.0+omega_n.*t5.*y_dot_n.*zeta_n.*4.0+omega_n.*t14.*y_dot_n.*zeta_n.*4.0+omega_n.*t15.*y_dot_n.*zeta_n.*4.0+t3.*t4.*x_ddot.*y_n.*2.0+t2.*t4.*y_n.*z_ddot.*2.0-h.*l_n.*psi_ddot.*x_n.*y_n-h_n.*l_n.*psi_ddot.*x_n.*y_n.*2.0-l_n.*t2.*x_ddot.*x_n.*y_n.*2.0+l_n.*t3.*x_n.*y_n.*z_ddot.*2.0+t3.*t4.*t6.*x_n.*y_n.*2.0).*(-1.0./2.0)];
dS = [mt1;mt2];
end
