function dS = MSDdyn4D_rotz(in1)
%MSDdyn4D_rotz
%    dS = MSDdyn4D_rotz(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-Jul-2025 14:14:36

l_n = in1(:,1);
omega_n = in1(:,2);
theta = in1(:,3);
theta_dot = in1(:,5);
theta_ddot = in1(:,4);
x_ddot = in1(:,6);
x_dot_n = in1(:,7);
x_n = in1(:,8);
y_ddot = in1(:,9);
y_dot_n = in1(:,10);
y_n = in1(:,11);
z_ddot = in1(:,12);
zeta_n = in1(:,13);
t2 = cos(theta);
t3 = sin(theta);
t4 = l_n.^2;
t5 = omega_n.^2;
t6 = theta_dot.^2;
t7 = x_dot_n.^2;
t8 = x_n.^2;
t9 = y_dot_n.^2;
t10 = y_n.^2;
t11 = t4+t8+t10;
t12 = 1.0./t11;
mt1 = [x_dot_n;y_dot_n;-t12.*(t7.*x_n+t9.*x_n-theta_ddot.*y_n.^3+l_n.*x_n.*z_ddot+t2.*t4.*x_ddot+t2.*t10.*x_ddot+t4.*t5.*x_n-t4.*t6.*x_n+t3.*t4.*y_ddot+t3.*t10.*y_ddot-t4.*theta_dot.*y_dot_n.*2.0-t10.*theta_dot.*y_dot_n.*2.0-t4.*theta_ddot.*y_n-t8.*theta_ddot.*y_n+omega_n.*t4.*x_dot_n.*zeta_n.*2.0+omega_n.*t8.*x_dot_n.*zeta_n.*2.0+omega_n.*t10.*x_dot_n.*zeta_n.*2.0+t3.*x_ddot.*x_n.*y_n-theta_dot.*x_dot_n.*x_n.*y_n.*2.0-t2.*x_n.*y_ddot.*y_n)];
mt2 = [-t12.*(t7.*y_n+t9.*y_n+theta_ddot.*x_n.^3+l_n.*y_n.*z_ddot-t3.*t4.*x_ddot-t3.*t8.*x_ddot+t4.*theta_dot.*x_dot_n.*2.0+t8.*theta_dot.*x_dot_n.*2.0+t4.*theta_ddot.*x_n+t10.*theta_ddot.*x_n+t2.*t4.*y_ddot+t2.*t8.*y_ddot+t4.*t5.*y_n-t4.*t6.*y_n+omega_n.*t4.*y_dot_n.*zeta_n.*2.0+omega_n.*t8.*y_dot_n.*zeta_n.*2.0+omega_n.*t10.*y_dot_n.*zeta_n.*2.0-t2.*x_ddot.*x_n.*y_n-t3.*x_n.*y_ddot.*y_n+theta_dot.*x_n.*y_dot_n.*y_n.*2.0)];
dS = [mt1;mt2];
end
