function Sd =odeMSD_6D_XYZ(t,S,time,g,h,h_n,omega_n,phi,phi_dot,phi_ddot,psi,psi_dot,psi_ddot,theta,theta_dot,theta_ddot,x_ddot,y_ddot,z_ddot,zeta_n)

%--------------------------------------------------------------------------
% ODE of MSD 6DOF Model
%    Auto-generated by MATLAB Symbolic Toolbox
%--------------------------------------------------------------------------

Sd = zeros(4,1);

x_n = S(1);
y_n = S(2);
x_dot_n = S(3);
y_dot_n = S(4);

if t >= 0 && t <= time(end)
   x_ddot  = spline(time,x_ddot,t);
   y_ddot  = spline(time,y_ddot,t);
   z_ddot  = spline(time,z_ddot,t);
   theta  = spline(time,theta,t);
   theta_dot  = spline(time,theta_dot,t);
   theta_ddot  = spline(time,theta_ddot,t);
   psi  = spline(time,psi,t);
   psi_dot  = spline(time,psi_dot,t);
   psi_ddot  = spline(time,psi_ddot,t);
   phi  = spline(time,phi,t);
   phi_dot  = spline(time,phi_dot,t);
   phi_ddot  = spline(time,phi_ddot,t);
else
   x_ddot  = 0;
   y_ddot  = 0;
   z_ddot  = 0;
   theta  = 0;
   theta_dot  = 0;
   theta_ddot  = 0;
   psi  = 0;
   psi_dot  = 0;
   psi_ddot  = 0;
   phi  = 0;
   phi_dot  = 0;
   phi_ddot  = 0;
end

% Equations of Motion
Sd = MSDdyn6D_XYZ([g,h,h_n,omega_n,phi,phi_ddot,phi_dot,psi,psi_ddot,psi_dot,theta,theta_ddot,theta_dot,x_ddot,x_dot_n,x_n,y_ddot,y_dot_n,y_n,z_ddot,zeta_n]);