function Sd =odeMSD_4D_rotx(t,S,time,h,h_n,l_n,omega_n,phi,phi_dot,phi_ddot,x_ddot,y_ddot,z_ddot,zeta_n)

%--------------------------------------------------------------------------
% ODE of MSD 4DOF Model
%    Auto-generated by MATLAB Symbolic Toolbox
%--------------------------------------------------------------------------

Sd = zeros(4,1);

x_n = S(1);
y_n = S(2);
x_dot_n = S(3);
y_dot_n = S(4);

if t >= 0 && t <= time(end)
   x_ddot  = spline(time,x_ddot,t);
   y_ddot  = spline(time,y_ddot,t);
   z_ddot  = spline(time,z_ddot,t);
   phi  = spline(time,phi,t);
   phi_dot  = spline(time,phi_dot,t);
   phi_ddot  = spline(time,phi_ddot,t);
else
   x_ddot  = 0;
   y_ddot  = 0;
   z_ddot  = 0;
   phi  = 0;
   phi_dot  = 0;
   phi_ddot  = 0;
end

% Equations of Motion
Sd = MSDdyn4D_rotx([h,h_n,l_n,omega_n,phi,phi_ddot,phi_dot,x_ddot,x_dot_n,x_n,y_ddot,y_dot_n,y_n,z_ddot,zeta_n]);